# Generated by Django 4.0.6 on 2022-07-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qcm',
            name='options_choix',
        ),
        migrations.AddField(
            model_name='qcm',
            name='option_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qcm',
            name='option_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qcm',
            name='option_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qcm',
            name='option_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qcm',
            name='reponse_correcte',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
