# Generated by Django 4.0.6 on 2022-07-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0002_remove_qcm_options_choix_qcm_option_1_qcm_option_2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qcm',
            options={'ordering': ['id'], 'verbose_name_plural': 'Qcm'},
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='option_4',
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='qcm',
            name='reponse_correcte',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(default='', max_length=255)),
                ('qcm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='qcm.qcm')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answers', to='qcm.question')),
            ],
        ),
    ]
