# Generated by Django 3.1.6 on 2022-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('enonce', models.CharField(max_length=10)),
                ('bonne_reponse', models.CharField(max_length=45)),
                ('cours', models.ManyToManyField(null=True, to='cours.Cours')),
            ],
        ),
    ]
