# Generated by Django 3.1.6 on 2022-08-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0003_remove_exercices_categorie_exercices_categorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercices',
            old_name='enonce',
            new_name='enonce_exercices',
        ),
        migrations.RenameField(
            model_name='exercices',
            old_name='nom',
            new_name='nom_exercices',
        ),
    ]
