# Generated by Django 4.0.6 on 2022-07-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_user', '0006_auto_20220713_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=45, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('date_annonce', models.DateTimeField(auto_now_add=True)),
                ('publie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='super_user.superuser')),
            ],
        ),
    ]
