# Generated by Django 3.1.6 on 2022-08-17 13:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_annonce', models.CharField(max_length=45, null=True)),
                ('description_annonce', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_annonce', models.DateTimeField(auto_now_add=True)),
                ('image_annonce', models.ImageField(blank=True, null=True, upload_to='static/images/annonces/')),
                ('fichier_annonce_pdf', models.FileField(blank=True, upload_to='static/fichiers/annonces/')),
            ],
            options={
                'ordering': ['date_annonce'],
            },
        ),
    ]
