# Generated by Django 4.0.6 on 2022-07-15 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annonce',
            options={'ordering': ['date_annonce']},
        ),
        migrations.AddField(
            model_name='annonce',
            name='image_annonce',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/annonces/'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='publie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
    ]
