# Generated by Django 3.1.6 on 2022-08-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_alter_annonce_options_annonce_image_annonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='fichier_pdf',
            field=models.FileField(blank=True, upload_to='static/fichiers/annonces/'),
        ),
    ]
