# Generated by Django 4.0.6 on 2022-07-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ficher_blog',
            field=models.FileField(blank=True, upload_to='file_uploads/blogs/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_Blog',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/blogs/'),
        ),
    ]
