# Generated by Django 3.1.6 on 2022-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('date_de_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=45)),
                ('code_postale', models.CharField(max_length=45)),
                ('ville', models.CharField(max_length=45)),
                ('num_tel', models.CharField(max_length=45, null=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('profile_image', models.ImageField(null=True, upload_to='static/images')),
                ('resume', models.FileField(upload_to='')),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
