# Generated by Django 3.1.6 on 2022-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleuser',
            old_name='code_postale',
            new_name='code_postal',
        ),
        migrations.RenameField(
            model_name='simpleuser',
            old_name='commentaire',
            new_name='présentation',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='avancement',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
