# Generated by Django 3.1.6 on 2022-08-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code_postal',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='file_uploads/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ville',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
