# Generated by Django 3.1.6 on 2022-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0002_auto_20220712_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='mot_de_passe',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
