# Generated by Django 3.1.6 on 2022-07-14 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simple_user', '0003_simpleuser_mot_de_passe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleuser',
            old_name='présentation',
            new_name='presentation',
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
