# Generated by Django 3.1.6 on 2022-07-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0004_auto_20220714_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='resume',
            field=models.FileField(upload_to='file_uploads/'),
        ),
    ]
