# Generated by Django 3.1.6 on 2022-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0005_auto_20220714_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleuser',
            name='resume',
            field=models.FileField(blank=True, upload_to='file_uploads/'),
        ),
    ]
