# Generated by Django 3.1.6 on 2022-08-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0005_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
