# Generated by Django 3.1.6 on 2022-08-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0006_auto_20220818_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_de_naissance',
        ),
    ]
