# Generated by Django 3.1.6 on 2022-08-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0007_remove_user_date_de_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(null=True),
        ),
    ]
