# Generated by Django 3.1.6 on 2022-08-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0008_user_date_de_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_de_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
