# Generated by Django 3.1.6 on 2022-08-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0010_auto_20220824_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_password',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
