# Generated by Django 3.1.6 on 2022-08-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_user', '0011_user_old_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_password',
        ),
    ]
