# Generated by Django 3.1.6 on 2022-07-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
                ('catégorie', models.CharField(max_length=10)),
                ('titre_module', models.CharField(max_length=45)),
                ('cours_module', models.CharField(max_length=45)),
                ('valeur_init', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
