# Generated by Django 3.1.6 on 2022-07-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='catégorie',
        ),
        migrations.AddField(
            model_name='cours',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.categorie'),
        ),
    ]
