# Generated by Django 4.0.6 on 2022-07-15 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('cours', '0002_auto_20220714_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categories.categorie'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='valeur_init',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
    ]
