# Generated by Django 4.0.6 on 2022-07-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_cours_categorie_alter_cours_valeur_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='ficher_cours',
            field=models.FileField(blank=True, upload_to='file_uploads/cours/'),
        ),
        migrations.AddField(
            model_name='cours',
            name='image_cours',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/cours/'),
        ),
    ]
