# Generated by Django 3.1.6 on 2022-07-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0006_auto_20220729_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='cours',
        ),
        migrations.AddField(
            model_name='cours',
            name='modules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cours.module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='titre_module',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
