# Generated by Django 3.1.6 on 2022-07-31 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0007_auto_20220731_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='cours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='cours.cours'),
        ),
    ]
