# Generated by Django 3.1.6 on 2022-07-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0008_auto_20220731_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='cours',
        ),
        migrations.AddField(
            model_name='cours',
            name='modules',
            field=models.ManyToManyField(to='cours.Module'),
        ),
    ]
