# Generated by Django 3.1.6 on 2022-08-01 08:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0009_auto_20220731_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_module', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('valeur_init', models.IntegerField(blank=True, default=25, null=True)),
                ('ficher_cours', models.FileField(blank=True, upload_to='file_uploads/cours/')),
            ],
        ),
        migrations.RemoveField(
            model_name='module',
            name='cours_module',
        ),
        migrations.RemoveField(
            model_name='module',
            name='ficher_cours',
        ),
        migrations.RemoveField(
            model_name='module',
            name='valeur_init',
        ),
        migrations.AddField(
            model_name='module',
            name='sous_module',
            field=models.ManyToManyField(to='cours.SousModule'),
        ),
    ]
