# Generated by Django 3.1.6 on 2022-08-01 08:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0011_auto_20220801_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='sous_module',
        ),
        migrations.AddField(
            model_name='module',
            name='cours_module',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='ficher_cours',
            field=models.FileField(blank=True, upload_to='file_uploads/cours/'),
        ),
        migrations.AddField(
            model_name='module',
            name='valeur_init',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
        migrations.DeleteModel(
            name='SousModule',
        ),
    ]
