# Generated by Django 3.1.6 on 2022-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0013_auto_20220801_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='sousmodule',
            name='num_module',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
