# Generated by Django 3.1.6 on 2022-07-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
