# Generated by Django 3.1.6 on 2022-07-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_user', '0002_superuser_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superuser',
            old_name='code_postale',
            new_name='code_postal',
        ),
    ]
