# Generated by Django 3.1.6 on 2022-07-13 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('super_user', '0003_auto_20220712_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='mot_de_passe',
            field=models.CharField(default=True, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='superuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
