# Generated by Django 3.1.6 on 2022-07-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_user', '0004_auto_20220713_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='date_de_naissance',
            field=models.DateField(blank=True),
        ),
    ]
