# Generated by Django 3.1.6 on 2022-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_user', '0005_auto_20220713_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='date_de_naissance',
            field=models.DateField(null=True),
        ),
    ]
